env:
  global:
    - CC_TEST_REPORTER_ID=16cae375508978df766d6cc58509c88f446739cc23a30cfdfd823ff921097f5f

language: php

php:
  - 7.2

# faster builds on new travis setup not using sudo
sudo: false

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.composer/vendor
    - vendor

services:
  - mysql

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client

install:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer install --prefer-dist --no-interaction
#  - cp config/db.dist.php config/db.php
  - cp config/test_db.travis.php config/db.php
  - cp config/test_db.travis.php config/test_db.php
  - cp config/params.dist.php config/params.php
  - cp config/web-local.dist.php config/web-local.php

before_script:
  - pip install --user codecov
  - mysql --version
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test CHARACTER SET utf8 COLLATE utf8_general_ci;'
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - php yii migrate --interactive=0 -c

script:
  - ./tests/bin/yii fixture/load '*' --interactive=0
  - ./vendor/bin/codecept run unit --coverage --coverage-xml

after_script:
  - mv tests/_output/coverage.xml clover.xml
  - ./cc-test-reporter after-build --coverage-input-type clover --id 12345 --exit-code $TRAVIS_TEST_RESULT

after_success:
  - codecov
