# https://travis-ci.org/opensourcewebsite-org/opensourcewebsite-org
# https://docs.travis-ci.com
language: php

php:
  - 7.4

# faster builds on new travis setup not using sudo
sudo: required

dist: bionic

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.composer/vendor
    - vendor

services:
  - mysql

before_install:
  - wget https://repo.mysql.com/mysql-apt-config_0.8.15-1_all.deb
  - sudo dpkg -i mysql-apt-config_0.8.15-1_all.deb
  - sudo apt-get update -q
  - sudo apt-get install -q -y --allow-unauthenticated -o Dpkg::Options::=--force-confnew mysql-server
  - sudo systemctl restart mysql
  - sudo mysql_upgrade

install:
  - cp .env.test.dist .env.test
  - cp config/params.dist.php config/params.php
  - cp config/web-local.dist.php config/web-local.php
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer install --prefer-dist --no-interaction

before_script:
  - php --version
  - php -m
  - mysql --version
  - mysql -e 'CREATE DATABASE IF NOT EXISTS opensourcewebsite_test CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;'
  - ./tests/bin/yii migrate --interactive=0 -c --silent-exit-on-exception=0

script:
  - ./tests/bin/yii fixture/load '*' --interactive=0 --silent-exit-on-exception=0
  - ./vendor/bin/codecept run -c ./codeception.yml --coverage
