# ----- OpenSourceWebsite Stellar Anchor <https://opensourcewebsite.org> -----

ACCOUNTS=[
"GC45AYPXRDYKK75HFWH5CUANMDFLQW34ZAXD5ZRTIAGS262XSBTFTCLH",
"GDOB5BAYE25LLEU6CCQCGGJB2ILUEIMA2DTQRGCVHX3XX2ATGMXP5ERH"
]

ORGANIZATION_NAME="OpenSourceWebsite"
ORGANIZATION_URL="https://opensourcewebsite.org"
ORGANIZATION_DESCRIPTIONL="OpenSourceWebsite (OSW) is open source website for global online social community, community-driven and available for free on https://opensourcewebsite.org"

[DOCUMENTATION]
ORG_NAME="OpenSourceWebsite"
ORG_DBA="OpenSourceWebsite"
ORG_URL="https://opensourcewebsite.org"
ORG_LOGO="https://opensourcewebsite.org/images/logo/logo.png"
ORG_DESCRIPTION="OpenSourceWebsite (OSW) is open source website for global online social community, community-driven and available for free on https://opensourcewebsite.org"
ORG_OFFICIAL_EMAIL="hello@opensourcewebsite.org"

[[CURRENCIES]]
code="USD"
issuer="GC45AYPXRDYKK75HFWH5CUANMDFLQW34ZAXD5ZRTIAGS262XSBTFTCLH"
status="live"
display_decimals=2
anchor_asset_type="fiat"
anchor_asset="USD"
name="OSW US Dollar"
desc="Cryptocurrency backed 1:1 to the US dollar."
image="https://opensourcewebsite.org/images/logo/logo.png"

[[CURRENCIES]]
code="THB"
issuer="GC45AYPXRDYKK75HFWH5CUANMDFLQW34ZAXD5ZRTIAGS262XSBTFTCLH"
status="live"
display_decimals=2
anchor_asset_type="fiat"
anchor_asset="THB"
name="OSW Thai Baht"
desc="Cryptocurrency backed 1:1 to the Thai Baht."
image="https://opensourcewebsite.org/images/logo/logo.png"

[[CURRENCIES]]
code="UAH"
issuer="GC45AYPXRDYKK75HFWH5CUANMDFLQW34ZAXD5ZRTIAGS262XSBTFTCLH"
status="live"
display_decimals=2
anchor_asset_type="fiat"
anchor_asset="UAH"
name="OSW Ukrainian Hryvna"
desc="Cryptocurrency backed 1:1 to the Ukrainian Hryvna."
image="https://opensourcewebsite.org/images/logo/logo.png"

[[CURRENCIES]]
code="RUB"
issuer="GC45AYPXRDYKK75HFWH5CUANMDFLQW34ZAXD5ZRTIAGS262XSBTFTCLH"
status="live"
display_decimals=2
anchor_asset_type="fiat"
anchor_asset="RUB"
name="OSW Russian Ruble"
desc="Cryptocurrency backed 1:1 to the Russian Ruble."
image="https://opensourcewebsite.org/images/logo/logo.png"

[[CURRENCIES]]
code="EUR"
issuer="GC45AYPXRDYKK75HFWH5CUANMDFLQW34ZAXD5ZRTIAGS262XSBTFTCLH"
status="live"
display_decimals=2
anchor_asset_type="fiat"
anchor_asset="EUR"
name="OSW Euro"
desc="Cryptocurrency backed 1:1 to the Euro."
image="https://opensourcewebsite.org/images/logo/logo.png"

[[CURRENCIES]]
code="SGD"
issuer="GC45AYPXRDYKK75HFWH5CUANMDFLQW34ZAXD5ZRTIAGS262XSBTFTCLH"
status="live"
display_decimals=2
anchor_asset_type="fiat"
anchor_asset="SGD"
name="OSW Singapore Dollar"
desc="Cryptocurrency backed 1:1 to the Singapore Dollar."
image="https://opensourcewebsite.org/images/logo/logo.png"

[[CURRENCIES]]
code="KRW"
issuer="GC45AYPXRDYKK75HFWH5CUANMDFLQW34ZAXD5ZRTIAGS262XSBTFTCLH"
status="live"
display_decimals=2
anchor_asset_type="fiat"
anchor_asset="KRW"
name="OSW South Korean Won"
desc="Cryptocurrency backed 1:1 to the South Korean Won."
image="https://opensourcewebsite.org/images/logo/logo.png"

[[CURRENCIES]]
code="BYN"
issuer="GC45AYPXRDYKK75HFWH5CUANMDFLQW34ZAXD5ZRTIAGS262XSBTFTCLH"
status="live"
display_decimals=2
anchor_asset_type="fiat"
anchor_asset="BYN"
name="OSW Belarusian Ruble"
desc="Cryptocurrency backed 1:1 to the Belarusian Ruble."
image="https://opensourcewebsite.org/images/logo/logo.png"

[[CURRENCIES]]
code="CNY"
issuer="GC45AYPXRDYKK75HFWH5CUANMDFLQW34ZAXD5ZRTIAGS262XSBTFTCLH"
status="live"
display_decimals=2
anchor_asset_type="fiat"
anchor_asset="CNY"
name="OSW Chinese Yuan"
desc="Cryptocurrency backed 1:1 to the Chinese Yuan."
image="https://opensourcewebsite.org/images/logo/logo.png"

[[CURRENCIES]]
code="PHP"
issuer="GC45AYPXRDYKK75HFWH5CUANMDFLQW34ZAXD5ZRTIAGS262XSBTFTCLH"
status="live"
display_decimals=2
anchor_asset_type="fiat"
anchor_asset="PHP"
name="OSW Philippine Peso"
desc="Cryptocurrency backed 1:1 to the Philippine Peso."
image="https://opensourcewebsite.org/images/logo/logo.png"

[[CURRENCIES]]
code="GBP"
issuer="GC45AYPXRDYKK75HFWH5CUANMDFLQW34ZAXD5ZRTIAGS262XSBTFTCLH"
status="live"
display_decimals=2
anchor_asset_type="fiat"
anchor_asset="GBP"
name="OSW British Pound"
desc="Cryptocurrency backed 1:1 to the British Pound."
image="https://opensourcewebsite.org/images/logo/logo.png"

[[CURRENCIES]]
code="MYR"
issuer="GC45AYPXRDYKK75HFWH5CUANMDFLQW34ZAXD5ZRTIAGS262XSBTFTCLH"
status="live"
display_decimals=2
anchor_asset_type="fiat"
anchor_asset="MYR"
name="OSW Malaysian Ringgit"
desc="Cryptocurrency backed 1:1 to the Malaysian Ringgit."
image="https://opensourcewebsite.org/images/logo/logo.png"

[[CURRENCIES]]
code="IDR"
issuer="GC45AYPXRDYKK75HFWH5CUANMDFLQW34ZAXD5ZRTIAGS262XSBTFTCLH"
status="live"
display_decimals=2
anchor_asset_type="fiat"
anchor_asset="IDR"
name="OSW Indonesian Rupiah"
desc="Cryptocurrency backed 1:1 to the Indonesian Rupiah."
image="https://opensourcewebsite.org/images/logo/logo.png"
