# OpenSourceWebsite Stellar Anchor <https://opensourcewebsite.org>
# https://github.com/stellar/stellar-protocol/tree/master/ecosystem

ACCOUNTS=[
"GC45AYPXRDYKK75HFWH5CUANMDFLQW34ZAXD5ZRTIAGS262XSBTFTCLH",
"GDOB5BAYE25LLEU6CCQCGGJB2ILUEIMA2DTQRGCVHX3XX2ATGMXP5ERH",
"GAUR5W3VKPRAYUUEH6VXJWIU4SQFACJIG7HM6YLTQTFBR56NAHQ5J3FC"
]

[DOCUMENTATION]
ORG_NAME="OpenSourceWebsite"
ORG_DBA="OpenSourceWebsite"
ORG_URL="https://opensourcewebsite.org"
ORG_LOGO="https://opensourcewebsite.org/images/logo/osw-white-logo.png"
ORG_DESCRIPTION="OpenSourceWebsite (OSW) - online community managed by users using electronic voting and modifying source code"
ORG_GITHUB="opensourcewebsite-org"
ORG_OFFICIAL_EMAIL="hello@opensourcewebsite.org"
ORG_SUPPORT_EMAIL="hello@opensourcewebsite.org"

[[CURRENCIES]]
code="OSW"
issuer="GC45AYPXRDYKK75HFWH5CUANMDFLQW34ZAXD5ZRTIAGS262XSBTFTCLH"
status="live"
display_decimals=7
anchor_asset_type="other"
name="OSW Crypto Fund"
desc="Cryptocurrency backed 1:1 to the share of OSW Crypto Fund."
image="https://opensourcewebsite.org/images/logo/osw-white-logo.png"

[[CURRENCIES]]
code="USD"
issuer="GC45AYPXRDYKK75HFWH5CUANMDFLQW34ZAXD5ZRTIAGS262XSBTFTCLH"
status="live"
display_decimals=2
anchor_asset_type="fiat"
anchor_asset="USD"
is_asset_anchored=true
is_unlimited=true
name="OSW US Dollar"
desc="Cryptocurrency backed 1:1 to the US dollar with a guaranteed weekly deposit income with floating rate. Backed funds are invested in the stock market for high frequency algorithmic trading."
conditions="0.5% weekly deposit income every Friday will added to accounts with a minimum balance of 50 USD."
redemption_instructions="This asset is redeemed by community ambassadors within accordance with National, Federal, State, and Local Laws."
image="https://opensourcewebsite.org/images/logo/osw-white-logo.png"

[[CURRENCIES]]
code="EUR"
issuer="GC45AYPXRDYKK75HFWH5CUANMDFLQW34ZAXD5ZRTIAGS262XSBTFTCLH"
status="live"
display_decimals=2
anchor_asset_type="fiat"
anchor_asset="EUR"
is_asset_anchored=true
is_unlimited=true
name="OSW Euro"
desc="Cryptocurrency backed 1:1 to the Euro with a guaranteed weekly deposit income with floating rate. Backed funds are invested in the stock market for high frequency algorithmic trading."
conditions="0.5% weekly deposit income every Friday will added to accounts with a minimum balance of 50 EUR."
redemption_instructions="This asset is redeemed by community ambassadors within accordance with National, Federal, State, and Local Laws."
image="https://opensourcewebsite.org/images/logo/osw-white-logo.png"

[[CURRENCIES]]
code="THB"
issuer="GC45AYPXRDYKK75HFWH5CUANMDFLQW34ZAXD5ZRTIAGS262XSBTFTCLH"
status="live"
display_decimals=2
anchor_asset_type="fiat"
anchor_asset="THB"
is_asset_anchored=true
is_unlimited=true
name="OSW Thai Baht"
desc="Cryptocurrency backed 1:1 to the Thai Baht with a guaranteed weekly deposit income with floating rate. Backed funds are invested in the stock market for high frequency algorithmic trading."
conditions="0.5% weekly deposit income every Friday will added to accounts with a minimum balance of 1000 THB."
redemption_instructions="This asset is redeemed by community ambassadors within accordance with National, Federal, State, and Local Laws."
image="https://opensourcewebsite.org/images/logo/osw-white-logo.png"

[[CURRENCIES]]
code="UAH"
issuer="GC45AYPXRDYKK75HFWH5CUANMDFLQW34ZAXD5ZRTIAGS262XSBTFTCLH"
status="live"
display_decimals=2
anchor_asset_type="fiat"
anchor_asset="UAH"
is_asset_anchored=true
is_unlimited=true
name="OSW Ukrainian Hryvna"
desc="Cryptocurrency backed 1:1 to the Ukrainian Hryvna with a guaranteed weekly deposit income with floating rate. Backed funds are invested in the stock market for high frequency algorithmic trading."
conditions="0.5% weekly deposit income every Friday will added to accounts with a minimum balance of 1000 UAH."
redemption_instructions="This asset is redeemed by community ambassadors within accordance with National, Federal, State, and Local Laws."
image="https://opensourcewebsite.org/images/logo/osw-white-logo.png"

[[CURRENCIES]]
code="RUB"
issuer="GC45AYPXRDYKK75HFWH5CUANMDFLQW34ZAXD5ZRTIAGS262XSBTFTCLH"
status="live"
display_decimals=2
anchor_asset_type="fiat"
anchor_asset="RUB"
is_asset_anchored=true
is_unlimited=true
name="OSW Russian Ruble"
desc="Cryptocurrency backed 1:1 to the Russian Ruble with a guaranteed weekly deposit income with floating rate. Backed funds are invested in the stock market for high frequency algorithmic trading."
conditions="0.5% weekly deposit income every Friday will added to accounts with a minimum balance of 2000 RUB."
redemption_instructions="This asset is redeemed by community ambassadors within accordance with National, Federal, State, and Local Laws."
image="https://opensourcewebsite.org/images/logo/osw-white-logo.png"

[[CURRENCIES]]
code="SGD"
issuer="GC45AYPXRDYKK75HFWH5CUANMDFLQW34ZAXD5ZRTIAGS262XSBTFTCLH"
status="live"
display_decimals=2
anchor_asset_type="fiat"
anchor_asset="SGD"
is_asset_anchored=true
is_unlimited=true
name="OSW Singapore Dollar"
desc="Cryptocurrency backed 1:1 to the Singapore Dollar."
image="https://opensourcewebsite.org/images/logo/osw-white-logo.png"

[[CURRENCIES]]
code="KRW"
issuer="GC45AYPXRDYKK75HFWH5CUANMDFLQW34ZAXD5ZRTIAGS262XSBTFTCLH"
status="live"
display_decimals=2
anchor_asset_type="fiat"
anchor_asset="KRW"
is_asset_anchored=true
is_unlimited=true
name="OSW South Korean Won"
desc="Cryptocurrency backed 1:1 to the South Korean Won."
image="https://opensourcewebsite.org/images/logo/osw-white-logo.png"

[[CURRENCIES]]
code="BYN"
issuer="GC45AYPXRDYKK75HFWH5CUANMDFLQW34ZAXD5ZRTIAGS262XSBTFTCLH"
status="live"
display_decimals=2
anchor_asset_type="fiat"
anchor_asset="BYN"
is_asset_anchored=true
is_unlimited=true
name="OSW Belarusian Ruble"
desc="Cryptocurrency backed 1:1 to the Belarusian Ruble."
image="https://opensourcewebsite.org/images/logo/osw-white-logo.png"

[[CURRENCIES]]
code="CNY"
issuer="GC45AYPXRDYKK75HFWH5CUANMDFLQW34ZAXD5ZRTIAGS262XSBTFTCLH"
status="live"
display_decimals=2
anchor_asset_type="fiat"
anchor_asset="CNY"
is_asset_anchored=true
is_unlimited=true
name="OSW Chinese Yuan"
desc="Cryptocurrency backed 1:1 to the Chinese Yuan."
image="https://opensourcewebsite.org/images/logo/osw-white-logo.png"

[[CURRENCIES]]
code="PHP"
issuer="GC45AYPXRDYKK75HFWH5CUANMDFLQW34ZAXD5ZRTIAGS262XSBTFTCLH"
status="live"
display_decimals=2
anchor_asset_type="fiat"
anchor_asset="PHP"
is_asset_anchored=true
is_unlimited=true
name="OSW Philippine Peso"
desc="Cryptocurrency backed 1:1 to the Philippine Peso."
image="https://opensourcewebsite.org/images/logo/osw-white-logo.png"

[[CURRENCIES]]
code="GBP"
issuer="GC45AYPXRDYKK75HFWH5CUANMDFLQW34ZAXD5ZRTIAGS262XSBTFTCLH"
status="live"
display_decimals=2
anchor_asset_type="fiat"
anchor_asset="GBP"
is_asset_anchored=true
is_unlimited=true
name="OSW British Pound"
desc="Cryptocurrency backed 1:1 to the British Pound."
image="https://opensourcewebsite.org/images/logo/osw-white-logo.png"

[[CURRENCIES]]
code="MYR"
issuer="GC45AYPXRDYKK75HFWH5CUANMDFLQW34ZAXD5ZRTIAGS262XSBTFTCLH"
status="live"
display_decimals=2
anchor_asset_type="fiat"
anchor_asset="MYR"
is_asset_anchored=true
is_unlimited=true
name="OSW Malaysian Ringgit"
desc="Cryptocurrency backed 1:1 to the Malaysian Ringgit."
image="https://opensourcewebsite.org/images/logo/osw-white-logo.png"

[[CURRENCIES]]
code="IDR"
issuer="GC45AYPXRDYKK75HFWH5CUANMDFLQW34ZAXD5ZRTIAGS262XSBTFTCLH"
status="live"
display_decimals=2
anchor_asset_type="fiat"
anchor_asset="IDR"
is_asset_anchored=true
is_unlimited=true
name="OSW Indonesian Rupiah"
desc="Cryptocurrency backed 1:1 to the Indonesian Rupiah."
image="https://opensourcewebsite.org/images/logo/osw-white-logo.png"
